/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AD3_ParserDecoder */

#ifndef _Included_AD3_ParserDecoder
#define _Included_AD3_ParserDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AD3_ParserDecoder
 * Method:    DecodeAD3Basic
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;ILjava/util/ArrayList;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_AD3_ParserDecoder_DecodeAD3Basic
  (JNIEnv *, jobject, jobject, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
